### PR TITLE
invertWithDoc

### PR DESCRIPTION
**Pull request by jahewson**
👋  Hi, this PR adds support for `ottypes` new `invertWithDoc(op, doc) -> op'` function.

Thanks!

### CODE REVIEW

**Comment by jhchen** [comment]
This code doesn't work

**Comment by jahewson** [comment]
Weird. I took a look and the problem is not with this PR but with `ot-fuzzer`. Coincidentally a variable named `doc` was left undefined by [this recent commit](https://github.com/ottypes/fuzzer/commit/72a27936d307bdbb610a2ba4b5941767b1687a70) and I have the misfortune of being the first CI build since then. I'll open a PR there to get it fixed.

Screen Shot 2020-09-21 at 10 38 03 AM

**Comment by jhchen** [comment]
I was not referring to the CI. I was referring to the code you added.

**Comment by jahewson** [comment]
As best I can tell the two operations are equivalent, I've written out a proof below. Let me know if there's something wrong.

---

1. ottypes defines `invertWithDoc(op, doc)` as

```
apply(apply(snapshot, op), invert(op, snapshot)) == snapshot
```

2. If we take the definition of `Delta.invert(base)`

```
base.compose(delta).compose(inverted) === base
```

3. write it using the same functional notation and terminology, `delta = op` and `base = snapshot`:

```
compose(compose(snapshot, op), inverted) === snapshot
```

4. then account for the fact that Delta's `compose` is actually named `apply` in ottypes:


```
apply(apply(snapshot, op), inverted) === snapshot
```

5. assuming that `inverted = invert(op, snapshot)`, we get the definition of ottype's `invertWithDoc`:

```
apply(apply(snapshot, op), invert(op, snapshot)) === snapshot
```

But the ottpyes docs are hazy on what `invert(op, snapshot)` means, I'm taking it to mean `invert(op)` with the constraint that `op` is based directly on `snapshot`.

**Pull request closed without merging**
