### PR TITLE
Update Readme concat function link

### PR DESCRIPTION
**Pull request by nbellowe**

### CODE REVIEW

**Comment by jhchen** [comment]
Thanks for pointing out a link was missing. Can you move it above the `diff` link so it corresponds correctly to the position in the README?

**Comment by nbellowe** [comment]
Sure

**Comment by jhchen** [comment]
I squashed your commits and merged it in. Thanks for the PR!

**Comment by nbellowe** [comment]
Any time.

**Comment by nbellowe** [comment]
And you just taught me a new git command! :)

**Pull request closed without merging**
