### PR TITLE
Bower package publish support

### LINKED ISSUE #11: Bower package
Ohai! Needed to use this OT document type to register it as a valid ShareJS type on the browser/client side and found that there wasn't a Bower package for it.

Is it possible to add support for Bower?

### PR DESCRIPTION
**Pull request by pedrosanta**
PR to add support to publish a Bower package, so one could use rich text OT type on the browser.

Added a `grunt build` task that cleans and browserifies the lib as a standalone - it will load the type as a global `richText`, probably this will need to be improved, I hereby open the discussion about it.

Also added a default `grunt` task that runs coverage, tests, and build tasks.

Closes #11.

### CODE REVIEW

**Comment by jhchen** [comment]
Thanks for taking the time to put together this PR. However I don't believe bower can see gitignored files so I don't believe this PR achieves its aims. Because bower lacks a build step, currently the only ways to support it requires the package maintainer either to commit built code or employ hacky workarounds that require manual releases. I tried the latter with another one of my libraries and it is a choice I regret and will not repeat with this library.

For users that insist on using bower, `bower install https://github.com/ottypes/rich-text` works just fine.

**Comment by pedrosanta** [comment]
And if one want to use a 'browserified' version of the OT type, do you see any alternative way on how that could be accomplished, I mean, without having to browserify it manually?

**Comment by morgante** [comment]
@pedrosanta This module is fully compatible with Browserify.

**Comment by pedrosanta** [comment]
@morgante but I would have to run browserify on the lib first if I wanted to use it on the browser, or am I missing something? :confused:

**Comment by pedrosanta** [comment]
It would be nice to have a bower package anyway. Gonna fork and keep a build branch for my purposes at the moment.

@jhchen thanks for taking the time to explain the reason/issue of maintaining a package. Cheers.

**Pull request closed without merging**
